[package]
name = "merge"
version = "0.1.0"
authors = ["Lyova Potyomkin <iamsuperman145@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.5.0"
rayon = "1.3.0"
num_cpus = "1.12.0"

[profile.release]
codegen-units = 1
lto = true
panic = 'abort'

# vim: ft=dosini
